"""Library-owned public capability descriptions shared by help and adapters."""

OPERATIONS = {
    "open-review": "Authorize portable disclosure for a retained object: {target_kind: plan|artifact|finding, target_id, scope?}.",
    "get-scoped-saved-outputs": "Read a bounded caller-authorized saved-output page: {offset?, limit?, sort_by?}; requires explicit review or collection authority.",
    "open-scoped-saved-output": "Attach one authorized saved export to its own retained workspace: {artifact_id, request_id?}.",
    "rename-scoped-saved-output": "CAS-rename an authorized saved export without rendering: {review_id, artifact_id, title, expected_plan_id, request_id?}.",
    "delete-scoped-saved-output": "CAS-delete an authorized generated export without affecting its source or plan: {review_id, artifact_id, expected_plan_id, request_id?}.",
    "describe-scoped-saved-output-media": "Describe authorized saved export bytes without exposing a path: {artifact_id}.",
    "read-scoped-saved-output-media": "Read a bounded authorized saved export chunk: {artifact_id, offset?, length?}.",
    "review-snapshot": "Read a bounded retained review: {review_id}.",
    "get-review-draft": "Read one exact retained raw draft: {review_id, base_plan_id}.",
    "get-review-finding-page": "Read a bounded linked finding candidate page: {review_id, finding_id, offset?, limit?}.",
    "navigate-review": "Set explicit versioned review focus: {review_id, view, expected_version, request_id?}.",
    "save-review-draft": "Retain raw editor values without applying a plan: {review_id, base_plan_id?, draft, expected_version}.",
    "apply-review-changes": "Apply exact workspace edits: {review_id, plan|plan_id, changes}.",
    "select-review-candidate": "Select a reviewed finding candidate into the same retained review: {review_id, finding_id, candidate_id, format?, profile?}.",
    "admit-operation": "Persist typed bounded work: render/preview {plan_id}; find/make {request, grant, format?, profile?}.",
    "get-operation": "Read a retained operation admission and terminal outcome: {operation_id}.",
    "get-operation-result-page": "Read bounded retained operation result bytes: {operation_id, offset?, limit?, review_id?}.",
    "cancel-operation": "Request cancellation of admitted work: {operation_id}.",
    "recover-operations": "Reconcile published retained output identities without replay: {}.",
    "describe-media": "Describe scoped artifact or evidence frame bytes: {review_id, kind, identity, index?}.",
    "read-media": "Read a bounded scoped media chunk: {review_id, media_id, offset?, length?}.",
    "get-workspace": "Resume saved editing state: {plan_id, artifact_id?}. Each saved output has its own draft.",
    "finish-workspace-export": "Attach an export to its own workspace and close its published source draft: {workspace_id, artifact_id}.",
    "save-workspace": "Save an immutable revision and advance its workspace: {workspace_id, plan, changes}.",
    "provider-login": "Explicit ChatGPT device sign-in: {provider: openai-chatgpt, timeout_seconds?}.",
    "caption-tracks": "List text and image caption tracks for a plan: {plan}.",
    "caption-image": "Resolve a retained original subtitle image for local inspection: {evidence_id, index}. No provider disclosure is implied.",
    "fonts": "List available font IDs and names: {}.",
    "output-profiles": "List deterministic output presets: {}.",
    "import-captions": "Import text cues or original image captions in a new plan revision: {plan, track?, offset?}.",
    "convert-captions": "Explicit local OCR of imported image captions; requires Tesseract; review resulting cues: {plan, language?}.",
    "rename-output": "Rename a saved export without rendering: {artifact_id, title}.",
    "delete-output": "Delete generated media and receipt, preserving source and plan: {artifact_id}.",
    "preferences": "Read workspace settings, appearance, model grant and credential availability: {}.",
    "configure": "Save workspace settings: {settings, model_grant?, appearance?}.",
    "review-frames": "Sample five local review frames for a plan: {plan}.",
    "artifact": "Get a saved artifact by identity: {artifact_id}.",
    "catalog": "Discover bounded source-name clues: {title?, scope?, limit?, scan_limit?}.",
    "source-details": "Inspect a catalog source and caption availability: {source_id, fingerprint_source?}.",
    "observe": "Extract timestamped local frame evidence: {source_id, times: [seconds,...]}.",
    "captions": "Search existing text captions: {source_id, query, track?, offset?, limit?}.",
    "get-evidence": "Load retained source observations: {evidence_id}.",
    "find": "Amplifier moment finding: {request: <FindRequest>, grant: <ModelGrant>}.",
    "get-finding": "Load a retained finding: {finding_id}.",
    "select": "Choose a retained candidate: {finding_id, candidate_id, format?, profile?, overlay?}.",
    "make": "Find and render a single candidate: {request, grant, format?, profile?}.",
    "inspect": "Inspect and fingerprint one local source: {source}.",
    "plan": "Create a retained plan: {source, start, end, format?, profile?, audio?, frame?, overlay?}.",
    "get-plan": "Load a retained plan: {plan_id}.",
    "revise": "Create a new revision: {plan: <plan object>, changes: {...}}.",
    "validate": "Validate a plan and current source: {plan: <plan object>}.",
    "preview": "Render the exact plan for local review: {plan: <plan object>}.",
    "render": "Publish artifact and receipt: {plan: <plan object>}.",
    "saved-outputs": "List published receipts, newest first by default: {sort_by?: newest|oldest|name|size, include_previews?}.",
}
